plugins {
    id 'com.android.application'
}

android {
    namespace 'com.flip.app'
    compileSdk 35

 dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}   defaultConfig {
        applicationId 'com.flip.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
